### PR TITLE
added feature to fetch any display team from gymkhana portal through graphql api 

### PR DESCRIPTION
**Pull request by manav1403**
Description-
    added dropdown select to select the year to fetch data for
    
    

    getTeam.js file defines functions which makes API calls to gymkhana portal adds block HTML to
        frontend

### CODE REVIEW

**Comment by 0xhrsh** [comment]
@manav1403 can you add the screenshot displaying UG Team PG Team?

**Comment by manav1403** [comment]
> @manav1403 can you add the screenshot displaying UG Team PG Team?

**Comment by harsh-not-haarsh** [comment]
Looks good enough

**Pull request merged**
